### ISSUE TITLE
NoSuchMethodError: Class 'MockFirebaseAuth' has no instance method 'verifyPhoneNumber' with matching arguments.

### ISSUE THREAD

**Issue by bettdouglas** [atn832/firebase_auth_mocks#42]
I have a usecase where I am calling the verifyPhoneNumber from the method _verify as shown below. 
In my test, I am replacing the firebaseAuth with  MockFirebaseAuth.  like below 

In the main code, I am using the FirebaseAuth.instance while in the test, I am using MockFirebaseAuth as shown 

```dart
// main.dart
AuthBloc(
    firebaseAuth: firebaseAuth,
)
```

```dart
// auth_bloc_test.dart
AuthBloc(
  firebaseAuth: MockFirebaseAuth(
    signedIn: false,
    mockUser: MockUser(
      phoneNumber: '0714109322',
    ),
  ),
)
```
Below is the how I am calling firebaseAuth.verifyPhoneNumber()....

```dart
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  AuthBloc({
    required this.firebaseAuth,
  }) : super(const _Initial()) {
    firebaseAuth.authStateChanges().listen((event) {
      if (event != null) {
        add(AuthEvent.gotUser(event));
      }
    });
  }

  final FirebaseAuth firebaseAuth;

  @override
  Stream<AuthState> mapEventToState(
    AuthEvent event,
  ) async* {
 // other code here
  }

  void _verify(String phoneNo) async {
    await firebaseAuth.verifyPhoneNumber(
      phoneNumber: phoneNo,
      verificationCompleted: (PhoneAuthCredential cred) {
        add(AuthEvent.verificationCompleted(cred));
      },
      verificationFailed: (exception) {
        add(AuthEvent.verificationFailed(exception));
      },
      codeSent: (verificationId, _) {
        add(AuthEvent.codeSent(verificationId));
      },
      codeAutoRetrievalTimeout: (verificationId) {
        add(AuthEvent.codeRetrievalTimeout(verificationId));
      },
      timeout: const Duration(minutes: 2),
    );
  }
}
```

I expected the method call to be mocked and authStateChange to trigger a change, but I am getting an error as shown below

> NoSuchMethodError: Class 'MockFirebaseAuth' has no instance method 'verifyPhoneNumber' with matching arguments.
Receiver: Instance of 'MockFirebaseAuth'
Tried calling: verifyPhoneNumber(phoneNumber: "phoneNumber", verificationCompleted: Closure: (PhoneAuthCredential) => void, verificationFailed: Closure: (FirebaseAuthException) => void, codeSent: Closure: (String, int?) => void, codeAutoRetrievalTimeout: Closure: (String) => void, autoRetrievedSmsCodeForTesting: null, timeout: Instance of 'Duration', forceResendingToken: 1)
Found: verifyPhoneNumber({required String phoneNumber, required (PhoneAuthCredential) => void verificationCompleted, required (FirebaseAuthException) => void verificationFailed, required (String, int?) => void codeSent, required (String) => void codeAutoRetrievalTimeout, String? autoRetrievedSmsCodeForTesting, Duration timeout, int? forceResendingToken}) => Future<void>

My pubspec.yaml is like below

```yaml
name: phone_firebase_auth
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  responsive_sizer: ^3.0.4+4
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  freezed_annotation: ^0.14.2
  firebase_auth_mocks: ^0.8.0
  country_list_pick:
  flutter_typeahead:
  phone_number:
  random_color_scheme:
  google_fonts: ^2.1.0
  logger_flutter:
    git:
      url: https://github.com/xaynetwork/logger_flutter.git
      ref: da8109894224abae1b8d1e9702e6478fb5ba2fdc

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  freezed: ^0.14.2
  build_runner:
  change_app_package_name:

flutter:
  uses-material-design: true
  generate: true
```

Kindly assist.
