### ISSUE TITLE
Unit test for firebase auth exceptions

### ISSUE THREAD

**Issue by anormaly-dev** [atn832/firebase_auth_mocks#96]
Hello, 

I am trying to write a unit test testing firebase authentication fail scenarios. From the read me you suggest to use:

```
whenCalling(Invocation.method(#signInWithCredential, null))
  .on(auth)
  .thenThrow(FirebaseAuthException(code: 'bla'));
expect(
  () => auth.signInWithCredential(FakeAuthCredential()),
  throwsA(isA<FirebaseAuthException>()),
);
```

Searching online, I don't understand why I cannot import / use `whenCalling`. Probably the flutter or dart version doesn't provide anymore this function? 

But anyway, I realized that I can simulate the error scenario like this: 
`firebaseAuthMock = MockFirebaseAuth(authExceptions: AuthExceptions(signInWithEmailAndPassword: FirebaseAuthException(code: 'bla')));`

Is it correct? if yes, I don't find it in the read me. 

I have this dependencies:

```
environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  firebase_storage: ^10.3.11
  firebase_messaging: ^13.1.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  loggy: ^2.0.1+1
  dots_indicator: ^2.1.0
  tab_indicator_styler: ^2.0.0
  percent_indicator: ^4.0.1
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^2.0.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_switch: ^0.3.2
  dio: ^4.0.6
  envied: ^0.2.4
  json_annotation: ^4.7.0
  image_picker: ^0.8.6
  overlay_support: ^2.1.0
  lite_rolling_switch: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_gherkin: ^2.0.0
  glob: ^2.1.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.2
  envied_generator: ^0.2.3+1
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  firebase_auth_mocks: ^0.8.7
```
